CREATE DATABASE DormitoryManagement

GO

USE [DormitoryManagement]

GO

CREATE TABLE [dbo].Manager(
	ManagerID INT NOT NULL PRIMARY KEY IDENTITY,
	FirstName NVARCHAR(26) NOT NULL,
	LastName NVARCHAR(26) NOT NULL,
	[Address] NVARCHAR(500),
	PhoneNumber NVARCHAR(11) NOT NULL,
	UserName VARCHAR(26) NOT NULL UNIQUE,
	[Password] VARCHAR(26) NOT NULL
);

GO

CREATE TABLE [dbo].Student(
	StudentID INT NOT NULL PRIMARY KEY IDENTITY,
	FirstName NVARCHAR(26) NOT NULL,
	LastName NVARCHAR(26) NOT NULL,
	NationalCode NVARCHAR(10) NOT NULL UNIQUE,
	PhoneNumber NVARCHAR(11) NOT NULL,
	[Address] NVARCHAR(500)
);

GO

CREATE TABLE [dbo].Dorm(
	DormID INT NOT NULL PRIMARY KEY IDENTITY,
	Capacity INT NOT NULL DEFAULT(0),
	NumberOfRooms INT NOT NULL DEFAULT(0),
	[Type] INT NOT NULL DEFAULT(0),
	[Address] NVARCHAR(500),
	Possibilies NVARCHAR(250) -- Spelling Mistake --
);

GO

CREATE TABLE [dbo].Room(
	RoomID INT NOT NULL PRIMARY KEY IDENTITY,
	DormName NVARCHAR(50) NOT NULL,
	Position INT NOT NULL,
	RoomNumber INT NOT NULL,
	Possibilities NVARCHAR(250),
	Caption NVARCHAR(500) NOT NULL,
	DormID INT NOT NULL FOREIGN KEY REFERENCES Dorm(DormID)
);

GO

CREATE TABLE [dbo].Reservations(
	ReservationsCode INT NOT NULL PRIMARY KEY IDENTITY,
	RoomID INT NOT NULL FOREIGN KEY REFERENCES Room(RoomID),
	StudentID INT NOT NULL FOREIGN KEY REFERENCES Student(StudentID),
	DateGetRoom DATETIME NOT NULL DEFAULT(GETDATE()),
	ReturningTheRoom DATETIME NOT NULL,
	Caption NVARCHAR(500) NOT NULL
);

GO
